# Synapse Page Admin
synapse_page_admin:
    resource: "@SynapsePageBundle/Resources/config/routing/admin.yml"
    prefix: "/{_locale}/admin"
    defaults:
        _locale: "%locale%"
    options:
        synapse_theme: demo

default_admin:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: "/%locale%/admin"
        permanent: true

# AppBundle
app_routing:
    resource: "@AppBundle/Resources/routing.yml"
    prefix: "/{_locale}/admin"
    defaults:
        _locale: "%locale%"
    options:
        synapse_theme: demo

# Front
synapse_page_content:
    resource: "@SynapsePageBundle/Resources/config/routing/content_type.yml"
    prefix: /{_locale}
    defaults:
        _locale: %locale%
    options:
        synapse_theme: demo
