services:
    app.social.controller:
        class: AppBundle\Component\Social\SocialController
        arguments:
            - '@synapse'

    # app.video.repository:
    #     class: AppBundle\ContentType\Video\Repository
    #     factory: ['@doctrine', getRepository]
    #     arguments: ['AppBundle\ContentType\Video\Entity']
